services:
# Our PostgresSQL database
  db:
# Using the latest PostgresSQL image
    image: postgres:latest
    ports:
      - "5433:5433"
    restart: always
    environment:
      POSTGRES_PASSWORD: Nami1224@@@@
# Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080